### ISSUE TITLE
Bad credentials not handled correctly

### ISSUE THREAD

**Issue by yippie** [joeferraro/MavensMate-SublimeText#609] opened 2015-07-20 19:26 UTC
If the MavensMate project cannot connect to the server due to bad credentials, this shows up in the mavensmate debug log however,  no MavensMate UI or actions will work, all of them fail with a 500 error from the MavensMate server.  This effectively breaks the project and requires that it must be deleted and re-created.

**Comment by joeferraro** [comment] 2015-07-20 19:33
dupe of https://github.com/joeferraro/MavensMate/issues/475

**Closed by joeferraro** 2015-07-20 19:33 UTC
