### ISSUE TITLE
Error creating new Project after MM 5.0 update

### ISSUE THREAD

**Issue by amitgithubuser** [joeferraro/MavensMate-SublimeText#684] opened 2015-10-01 19:41 UTC
Not able to create new project after MM 5.0 update

I am using windows 7. I have Mavensmate app installed and I am trying to create new project.
Attached is the error received when creating new project.

![mavensmate-error-new-project](https://cloud.githubusercontent.com/assets/5687840/10231813/6fd980d8-684a-11e5-9e8c-321f7593bec6.PNG)

**Comment by joeferraro** [comment] 2015-10-01 19:54
@amitgithubuser  duplicate of https://github.com/joeferraro/MavensMate-app/issues/43

**Closed by joeferraro** 2015-10-01 19:54 UTC
