### ISSUE TITLE
UNSUPPORTED_CLIENT: TLS 1.0

### ISSUE THREAD

**Issue by Jeremywhiteley** [joeferraro/MavensMate-SublimeText#806] opened 2016-06-25 20:56 UTC
Now I get this error?  

Server raised fault: 'UNSUPPORTED_CLIENT: TLS 1.0 has been disabled in this organization. Please use TLS 1.1 or higher when connecting to Salesforce using https.'

What is the fix?   1.1 is now required.

**Comment by bkdesu** [comment] 2016-06-25 23:11
facing the same issue after sandbox refresh.

**Comment by MirandaJanell** [comment] 2016-06-26 18:44
The "Require TLS 1.1 or higher for HTTPS connections" critical update auto-activation date for sandboxes is June 25, 2016. The supporting documentation is at https://help.salesforce.com/apex/HTViewSolution?urlname=TLS-1-0-Disablement-Critical-Update-Console-CRUC-Setting&language=en_US

This is a duplicate of Issue #769, so the discussion should continue there.

**Comment by Jeremywhiteley** [comment] 2016-06-26 19:23
This doesn't work!   Why can't you provide clear directions on how to how to fix this issue!  It's june 26th,  we are passed the salesforce.com deadline.

**Comment by ckoppelman** [comment] 2016-06-27 15:14
The fix is to use MavensMate v7.0.  See #769

**Comment by amilabdallah** [comment] 2016-06-28 18:42
Yes updating to mavensmate v7.0 fixes the TLS issue, but since the summer '16 update you will start facing this issue with the beta 7 version:  https://github.com/joeferraro/MavensMate-SublimeText/issues/783

**Comment by BobHatcher** [comment] 2016-06-28 20:38
Assuming you're using MavensMate for Sublime Text:

1. Download the MavensMate.app from [GitHub](https://github.com/joeferraro/MavensMate-app/releases/tag/v0.0.10).
2. Sublime Text Menu -> Preferences -> Package Settings -> Package Control -> Settings - User
![screen shot 2016-06-28 at 3 55 45 pm](https://cloud.githubusercontent.com/assets/12090526/16431458/ad112a44-3d4e-11e6-867b-977b6d60d710.png)

3. In this file add the following:
"install_prereleases":
[
"MavensMate"
],
(No trailing comma if it's the last clause in the file.) Note you can NOT do this for the All User settings.
![screen shot 2016-06-28 at 3 57 33 pm](https://cloud.githubusercontent.com/assets/12090526/16431455/a3d9e182-3d4e-11e6-8af1-ba691c59f76c.png)

4. Quit and restart Sublime Text.
5. In Sublime, use COMMAND+SHIFT+P and type “Package Control”. Run “Upgrade Package”.
6.  Quit and restart Sublime Text.
7. Run the MavensMate app and add your source code directory in Settings.
![screen shot 2016-06-28 at 4 10 09 pm](https://cloud.githubusercontent.com/assets/12090526/16431456/a7eb69a8-3d4e-11e6-9979-a5837056cf59.png)

**Closed** 2016-09-19 12:38 UTC
