### ISSUE TITLE
Unable to create new project

### ISSUE THREAD

**Issue by AJJJAIAH** [joeferraro/MavensMate-SublimeText#627] opened 2015-08-18 06:41 UTC
Hello,
I have installed Sublime and installed mavensmate to it.
Able to see Mavenmate tab on Sublime Text3, and set workspace to my local directory path to created new project.
But when i try to create new project from,
MavensMate --> Project --> New Project , i get below error.

[OPERATION FAILED]: Could not find the mm executable. Please run MavensMate > Install/Update MavensMate API (mm) to install mm to your MavensMate for Sublime Text plugin directory.

Even i tried to "Install Mavensmate API (mm)" which showed in error log , but no luck. Error is still appearing.

Can someone please help me here.

**Comment by joeferraro** [comment] 2015-08-20 11:07
duplicate of https://github.com/joeferraro/MavensMate-SublimeText/issues/513

**Closed by joeferraro** 2015-08-20 11:07 UTC
