### ISSUE TITLE
Right-click command "Refresh Resource Bundle(s)" is not refreshing static resources in bundle

### ISSUE THREAD

**Issue by gazazello** [joeferraro/MavensMate-SublimeText#547] opened 2015-02-23 22:06 UTC
I am not using regular "Refresh from Server...", but the resouce-bundle specific command "Refresh Resource Bundle(s)". So when I run the command, mavensmate's console appears for 1 second and closes. Resource bundle files are not updated. I have to recreate bundle to get the fresh versions of static resource bundle files.

**Comment by ralphcallaway** [comment] 2015-04-18 17:08
potential duplicate of #551 

@gazazello can you enable plugin logging and post the log details? that should provide some insight as to why this might be occurring http://mavensmate.com/Plugins/Sublime_Text/Plugin_Logging

closing for now until there are some diagnostic details for us to look into

**Closed by ralphcallaway** 2015-04-18 17:08 UTC
