### ISSUE TITLE
Facing issue while creating a new project

### ISSUE THREAD

**Issue by Shatank13** [joeferraro/MavensMate-SublimeText#514] opened 2014-11-15 21:01 UTC
I recently got the portable verison of sublime text and after installing mavens mate when I try to create a new project I run into the following issue. Kindly help me out here

[MAVENSMATE]: Calling mm_interface
[MAVENSMATE]: OPERATION: new_project
[MAVENSMATE]: {}
[MAVENSMATE]: mm command: 
[MAVENSMATE]: "C:\Program Files\Sublime Text 3\Data\Packages\User\MavensMate\mm\mm.exe" -c SUBLIME_TEXT_3 --ui -o new_project
[MAVENSMATE]: {}
[MAVENSMATE]: response from mm: Traceback (most recent call last):
File "<string>", line 6, in <module>
File "C:\Users\Administrator\Desktop\PyInstaller-2.1\PyInstaller\loader\pyi_importers.py", line 270, in load_module
File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm", line 6, in <module>
File "C:\Users\Administrator\Desktop\PyInstaller-2.1\PyInstaller\loader\pyi_importers.py", line 270, in load_module
File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.request", line 6, in <module>
File "C:\Users\Administrator\Desktop\PyInstaller-2.1\PyInstaller\loader\pyi_importers.py", line 270, in load_module
File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.config", line 55, in <module>
File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.config", line 38, in __get_base_path

AttributeError: 'module' object has no attribute '_MEIPASS'

**Comment by ralphcallaway** [comment] 2015-05-05 09:56
@Shatank13 this appears to be an issue with the python installer

happened to get to a duplicate of your bug #566 which includes alternative options than the python installer that have worked for most users, closing this one out

**Closed by ralphcallaway** 2015-05-05 09:56 UTC
