### ISSUE TITLE
It takes a couple of times to deploy resource bundle to sf.

### ISSUE THREAD

**Issue by sk29110** [joeferraro/MavensMate-SublimeText#551] opened 2015-03-04 15:02 UTC
I have experienced this problem for a last couple of months. Anyone has the same issue?
Basically when you go "Deploy Resource Bundle" It doesn't deploy the source to SF. I checked the my environment to check by going "Set Up" > "Static Resoruce" and download the package. It didn't get updated. However, if I try a couple of times it does eventually deployed. Have we fix this issue? Or I am setting some of option wrong?

Sublime Text 3 Build 3065
Mavensmate : v4.0.2
mm_api_version: 30.0
mm_compile_with_tooling_api: false

**Comment by sk29110** [comment] 2015-03-10 16:15
Is this only me or anyone experience the same problem?

**Comment by ralphcallaway** [comment] 2015-04-16 02:57
@sk29110 can you enable plugin logging and post the log details? that should provide some insight as to why this might be occurring http://mavensmate.com/Plugins/Sublime_Text/Plugin_Logging

**Comment by ralphcallaway** [comment] 2015-04-18 17:06
closing this for now, re-open if the issue is still occurring with logs

**Closed by ralphcallaway** 2015-04-18 17:06 UTC
