### ISSUE TITLE
Command new project throws exception

### ISSUE THREAD

**Issue by dylanmensaert** [joeferraro/MavensMate-SublimeText#475] opened 2014-09-08 08:44 UTC
[MAVENSMATE]: OPERATION: new_project
[MAVENSMATE]: {}
[MAVENSMATE]: mm command: 
[MAVENSMATE]: /home/dylan/.config/sublime-text-3/Packages/User/MavensMate/mm/mm -o new_project --ui -c SUBLIME_TEXT_3
[MAVENSMATE]: {}
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/home/dylan/.config/sublime-text-3/Packages/MavensMate/lib/mm_interface.py", line 327, in run
    response_body = '\n'.join(mm_response)
TypeError: sequence item 0: expected str instance, bytes found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "/home/dylan/.config/sublime-text-3/Packages/MavensMate/lib/mm_interface.py", line 331, in run
    strs.append(line.decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 137: invalid start byte

**Comment by ralphcallaway** [comment] 2015-04-01 01:38
duplicate of #536, closing tis one as #536 has more diagnostic details

**Closed by ralphcallaway** 2015-04-01 01:38 UTC
