### ISSUE TITLE
Cannot create project from existing folder

### ISSUE THREAD

**Issue by yippie** [joeferraro/MavensMate-SublimeText#610] opened 2015-07-20 19:39 UTC
In MM v5., open a cloned folder in Sublime Text that has a SF src folder but no MM config folder.  Right click on the root folder, select MavensMate -> Create MavensMate Project ...

The above action results in the following error:
Operation: Handling requested operation...
Timestamp: Mon, 20 Jul 2015 14:33:59
   Result: [ERROR]: Command not supported: new_project_from_existing_directory

MavensMate.log:

2015-07-20T19:33:59.215Z - debug: Processing request GET for URL: /status?id=44a38020-2f16-11e5-8ed1-ef260bbb0783
2015-07-20T19:33:59.215Z - debug:  id=44a38020-2f16-11e5-8ed1-ef260bbb0783
2015-07-20T19:35:45.126Z - debug: Processing request POST for URL: /execute?command=new_project_from_existing_directory&async=1
2015-07-20T19:35:45.126Z - debug:  directory=/Users/kaia/Google Drive/workspace/myWorkspace
2015-07-20T19:35:45.127Z - info: 

==================> executing command: new_project_from_existing_directory

2015-07-20T19:35:45.127Z - info: executeCommandForProject payload is: {"directory":"/Users/kaia/Google Drive/workspace/BMS"}
2015-07-20T19:35:45.127Z - info: handling command result: 
2015-07-20T19:35:45.127Z - debug:  Error: Command not supported: new_project_from_existing_directory
    at /Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/lib/mavensmate/client.js:330:16
    at tryCatch2 (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:53:21)
    at Promise._resolveFromResolver (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:544:13)
    at new Promise (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:82:37)
    at Client.executeCommandForProject (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/lib/mavensmate/client.js:325:10)
    at UIServer.executePostHandler (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/lib/mavensmate/ui/server.js:102:10)
    at Layer.handle [as handle_request] (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/express/lib/router/layer.js:82:5)
    at next (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/express/lib/router/route.js:100:13)
    at Route.dispatch (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/express/lib/router/route.js:81:3)
    at Layer.handle [as handle_request] (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/express/lib/router/layer.js:82:5)
    at /Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/express/lib/router/index.js:235:24
    at Function.proto.process_params (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/express/lib/router/index.js:313:12)
    at /Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/express/lib/router/index.js:229:12
    at Function.match_layer (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/express/lib/router/index.js:296:3)
    at next (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/express/lib/router/index.js:190:10)
    at /Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/express/lib/router/index.js:215:18
2015-07-20T19:35:45.130Z - debug: Processing request GET for URL: /status?id=83c63860-2f16-11e5-8ed1-ef260bbb0783
2015-07-20T19:35:45.130Z - debug:  id=83c63860-2f16-11e5-8ed1-ef260bbb0783
 

mmst.log:
Calling cli
OPERATION: new_project_from_existing_directory
{'body': {'directory': '/Users/kaia/Google Drive/workspace/myWorkspace'}}
http://localhost:52765/execute?command=new_project_from_existing_directory&async=1
b'{"directory": "/Users/kaia/Google Drive/workspace/myWorkspace"}'
{'id': '83c63860-2f16-11e5-8ed1-ef260bbb0783', 'operation': 'new_project_from_existing_directory', 'complete': True, 'stack': 'Error: Command not supported: new_project_from_existing_directory\n    at /Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/lib/mavensmate/client.js:330:16\n    at tryCatch2 (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:53:21)\n    at Promise._resolveFromResolver (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:544:13)\n    at new Promise (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:82:37)\n    at Client.executeCommandForProject (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/lib/mavensmate/client.js:325:10)\n    at UIServer.executePostHandler (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/lib/mavensmate/ui/server.js:102:10)\n    at Layer.handle [as handle_request] (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/express/lib/router/layer.js:82:5)\n    at next (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/express/lib/router/route.js:100:13)\n    at Route.dispatch (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/express/lib/router/route.js:81:3)\n    at Layer.handle [as handle_request] (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/express/lib/router/layer.js:82:5)\n    at /Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/express/lib/router/index.js:235:24\n    at Function.proto.process_params (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/express/lib/router/index.js:313:12)\n    at /Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/express/lib/router/index.js:229:12\n    at Function.match_layer (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/express/lib/router/index.js:296:3)\n    at next (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/express/lib/router/index.js:190:10)\n    at /Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/express/lib/router/index.js:215:18', 'error': 'Command not supported: new_project_from_existing_directory'}
Could not load json response from mavensmate
{'id': '83c63860-2f16-11e5-8ed1-ef260bbb0783', 'operation': 'new_project_from_existing_directory', 'complete': True, 'stack': 'Error: Command not supported: new_project_from_existing_directory\n    at /Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/lib/mavensmate/client.js:330:16\n    at tryCatch2 (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:53:21)\n    at Promise._resolveFromResolver (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:544:13)\n    at new Promise (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:82:37)\n    at Client.executeCommandForProject (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/lib/mavensmate/client.js:325:10)\n    at UIServer.executePostHandler (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/lib/mavensmate/ui/server.js:102:10)\n    at Layer.handle [as handle_request] (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/express/lib/router/layer.js:82:5)\n    at next (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/express/lib/router/route.js:100:13)\n    at Route.dispatch (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/express/lib/router/route.js:81:3)\n    at Layer.handle [as handle_request] (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/express/lib/router/layer.js:82:5)\n    at /Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/express/lib/router/index.js:235:24\n    at Function.proto.process_params (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/express/lib/router/index.js:313:12)\n    at /Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/express/lib/router/index.js:229:12\n    at Function.match_layer (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/express/lib/router/index.js:296:3)\n    at next (/Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/express/lib/router/index.js:190:10)\n    at /Users/kaia/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/express/lib/router/index.js:215:18', 'error': 'Command not supported: new_project_from_existing_directory'}

**Comment by joeferraro** [comment] 2015-07-20 19:41
dupe of https://github.com/joeferraro/MavensMate/issues/464

**Closed by joeferraro** 2015-07-20 19:41 UTC
