### ISSUE TITLE
Creating new project throws [Error 5] Access is denied

### ISSUE THREAD

**Issue by lewafa** [joeferraro/MavensMate-SublimeText#542] opened 2015-02-17 11:10 UTC
When I try to create a new Project, it always gives me the below error.
[Error 5] Access is denied

How do I fix this? here is the log

[MAVENSMATE UI]: >>> request is not ready
[MAVENSMATE UI]: {"status": "pending", "id": "wybu0nh7"}
[MAVENSMATE UI]: >>> got a response body
[MAVENSMATE UI]: {"body": "[Error 5] Access is denied", "stack_trace": "Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 93, in execute\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.commands.project\", line 39, in execute\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.project\", line 120, in retrieve_and_write_to_disk\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.util\", line 278, in rename_directory\nWindowsError: [Error 5] Access is denied\n", "success": false}

[MAVENSMATE UI]: >>> handling request
[MAVENSMATE UI]: /status?id=wybu0nh7
[MAVENSMATE UI]: >>> status request
[MAVENSMATE UI]: >>> params: 
[MAVENSMATE UI]: {'id': 'wybu0nh7'}
[MAVENSMATE UI]: >>> request id: wybu0nh7
[MAVENSMATE UI]: >>> async queue: 
[MAVENSMATE UI]: {'wybu0nh7': <BackgroundWorker(Thread-19, stopped 14412)>}
[MAVENSMATE UI]: found thread in request queue, checking if alive
[MAVENSMATE UI]: False
[MAVENSMATE UI]: >>> request is ready, returning response

**Comment by bmoothedan** [comment] 2015-02-27 15:13
I get the exact same error. I'm running Windows 8.1 and my working folder is C:\Dev with full access set to Everyone for this folder. Any help resolving this issue will be appreciated.

![image](https://cloud.githubusercontent.com/assets/9263024/6414915/3101644c-be69-11e4-9495-f3b6979ad0f5.png)

**Comment by talcarmi** [comment] 2015-03-12 12:08
try using "/" instead of "\\" when specifying the directory of the workspace. Worked for me

**Comment by bmoothedan** [comment] 2015-03-17 13:24
I tried the following but none of the options worked:


"mm_workspace" : "C:\\Dev",

"mm_workspace" : "C://Dev",

"mm_workspace" : "C://Dev//",

"mm_workspace" : "C:\\Dev\\",



Everyone has full access rights to the Dev folder on my machine. I still get the [Error 5] Access is denied error upon creating a new Project through the Chrome browser.


I can see that the following files and folders are created but perhaps something goes wrong during the unarchival process?


"C:\Dev\Test12\unpackaged"
"C:\Dev\Test12\metadata.zip"


Any other options that I can try?




Thank you,
-Binu





From: talcarmi
Sent: ‎Thursday‎, ‎March‎ ‎12‎, ‎2015 ‎8‎:‎09‎ ‎AM
To: joeferraro/MavensMate-SublimeText
Cc: Binu Moothedan





try using "/" instead of "\" when specifying the directory of the workspace. Worked for me

**Comment by talcarmi** [comment] 2015-03-17 17:41
Try C:/Dev, that should solve it

**Comment by bmoothedan** [comment] 2015-03-17 18:32
☹ That didn’t work either. I use Windows 8.1. Maybe it’s something related to that?






Thank you,
-Binu





From: talcarmi
Sent: ‎Tuesday‎, ‎March‎ ‎17‎, ‎2015 ‎1‎:‎41‎ ‎PM
To: joeferraro/MavensMate-SublimeText
Cc: Binu Moothedan





Try C:/Dev, that should solve it

**Comment by VinitKumar-** [comment] 2015-04-04 20:08
Hi,

I am facing this issue.Please suggest the fix.

**Comment by bmoothedan** [comment] 2015-04-05 13:38
I doubt if there's a fix yet.

**Comment by ralphcallaway** [comment] 2015-04-06 15:51
anyone whose got windows 8.1 going, please consider helping out here! 

this is a community project, so there isn't funding or full time developers are any of that, and at least for me, I don't have a machine with windows 8.1 so I'm kind of stuck

if you've only created issues, but haven't fixed any yet, now's the time to make a difference

**Comment by bmoothedan** [comment] 2015-04-06 15:52
I don't do much of development but I can definitely help test this issue if
someone has a fix. I have Windows 8.1

**Comment by ralphcallaway** [comment] 2015-04-18 17:26
so i got win 8.1 up and running, but this doesn't seem to happen for me

i hate to say it, but have you considered wiping out the package and re-installing, and moving around your workspace to other folders to see if they have issues there as well?

the exception is erroring out when trying to rename a folder somewhere, but seems like it didn't actually complete unzipping things first, you might take a look at the permissions on the test12 folder and see if anything looks off there

given the project folder was created in your workspace and the code was downloaded, you might also see if unzipping the file causes any issues ...

**Comment by ralphcallaway** [comment] 2015-04-18 17:27
as a potential work around you might consider getting a project going with ant or eclipse to get the files locally, and then add the project to mavens mate

**Comment by ralphcallaway** [comment] 2015-04-18 18:06
one other consideration, you might also consider install the mm core api via pip (see http://mavensmate.com/Getting_Started/Users) or via source code (see http://mavensmate.com/Getting_Started/Developers), several users have found that fixes low level permissions and encoding issues

closing for now, please re-open if none of these steps get you moving

**Closed by ralphcallaway** 2015-04-18 18:06 UTC

**Comment by enricmora** [comment] 2015-04-29 17:07
Hi guys,
I was receiving this error on windows 8.1 until I removed all numbers of the project name, and then all worked fine.  I hope it helps.

**Comment by jeffrutter** [comment] 2015-06-12 17:45
Hi all,

I wanted to share what was the solution for me on this issue. I tried to create a new project in Mavensmate and was getting the same error code. I realized after uninstalling the McAfee trial software on my computer (To reinstall something better....)  that it definitely had something to do with the firewall settings the trial software was using. My new AV service prompted me to decide whether to block the plug-in and after opting out of that I was able to create the 3 projects I had been trying to create all along!

I hope this helps!

**Comment by nexpath** [comment] 2015-08-18 22:26
you need to open port 7777 in your firewall if you have one. Try disabling it and if the error goes away, then you can add a rule to allow connections to your pc on port 7777 which will solve the problem permanently.

**Comment by jduelfer** [comment] 2015-10-14 16:16
@nexpath THANK YOU!! Open port 7777 on Windows works for me.

**Comment by JACKSANFORD** [comment] 2015-12-11 22:32
@nexpath Thanks so much! 7777 open worked for me too.

**Comment by jonathanwiesel** [comment] 2016-01-29 11:22
I was getting the error and it seems the only way to create a project is to change from:

C:\\folder to C:/folder

The next project I create shows the same error, but changing back

C:/folder to C:\\folder 

seems to create it successfully, I need to alternate configuration every time I create a project.

I'm on Windows 10.

Any ideas about this?

**Comment by jduelfer** [comment] 2016-01-29 12:01
@jonathanwiesel I don't use Windows much, but when I do...on my work computer I use D:\\path\\to\\folder with double slashes for my mm_workspace and it works. Hope it helps.

**Comment by jonathanwiesel** [comment] 2016-01-29 12:03
@jduelfer yep tried that but still need to change from one to another between project creations for it to work. Weird

**Comment by jonathanwiesel** [comment] 2016-01-29 12:48
@bmoothedan I'm getting the same response in the console as you, did you manage to solve the issue?

**Comment by vicrumnaug** [comment] 2016-03-20 23:13
Hey guys, I had the same problem. I have figured out the issue. It is caused by your firewall or antivirus software blocking your browser to create mavensmate folder in c: drive. Please disable your firewall or antivirus software and try. It should definitely work. You can then turn it back on.

**Comment by Vinu-M** [comment] 2016-06-14 14:19
Hi All,

To fix this i have done the below steps,

1. Restarted the system
2. Disabled the firewall
3. i have set the location like this in both user and default  "mm_workspace" : "C:\\Applications\\SF",


Above steps fixed the issue, happy coding:)

**Comment by VictorKilo** [comment] 2016-07-14 17:29
**If you have Dropbox or Google Drive, try pausing or closing the programs while creating your project!**

If your project is within your Dropbox/Drive directory, the software will want to start uploading the files as soon as the folder is created which will cause an access problem.
