### ISSUE TITLE
Error: Could not create Trace Flags: LogType is required.: LogType

### ISSUE THREAD

**Issue by agentgill** [joeferraro/MavensMate-SublimeText#781] opened 2016-04-25 15:20 UTC
Not sure where and how to fix this one. I'm guessing some setting has been knocked out.

Using Mac OS, Sublime Text and MavensMate v7

**Comment by sp0ken** [comment] 2016-05-13 08:54
Same issue here and same softwares

**Comment by dfully0814** [comment] 2016-05-23 20:43
Same issue here.

**Comment by jungblud** [comment] 2016-06-02 15:01
Ditto.

**Comment by ckoppelman** [comment] 2016-06-27 16:37
Duplicate of #126

**Closed** 2016-09-19 12:38 UTC
